### PR TITLE
bump parent pom

### PR DESCRIPTION
**Pull request by casz**
blocking #14

### CODE REVIEW

**Comment by chriskilding** [comment]
When I tried using v3.55 in my username/password bug fix branch, some of the tests in `org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite` became flaky. Sometimes they failed with a socket read timeout, sometimes not. I don't know the cause, but rolling back to 3.50 stopped the failures.

As a result I don't think we can adopt v3.55 at the moment.

**Comment by casz** [comment]
Disable the flaky test?

**Comment by casz** [comment]
@chriskilding not sure which test your referring to?
https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/git-plugin-username-password-bug/src/test/java/io/jenkins/plugins/credentials/secretsmanager/StandardUsernamePasswordCredentialsIT.java something here?

**Comment by chriskilding** [comment]
It was a test in `org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite` (but didn't say which one). The stack trace had something about the HtmlUnit WebClient in it.

**Comment by casz** [comment]
There were breaking changes in the HtmlUnit library so that makes sense. That means we should fix them not ignore the problem.

**Comment by casz** [comment]
@chriskilding this should be fixed in newer version: https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-3.56

**Comment by chriskilding** [comment]
There are some extra dependencies that have to be pinned to satisfy the Maven enforcer plugin. I did some work on identifying them in #10 so will need to copy some of that work into your PR. I encountered some noclassdeffound errors when doing that, which stayed hidden till runtime, so could you merge your dependency bumping PRs into #14? Then we can test all the changes together.

**Comment by chriskilding** [comment]
closing in favour of #14

**Pull request closed without merging**
