### PR TITLE
[feature] Allow AWS static keypairs to be used for authN

### LINKED ISSUE #94: Allow AWS access key to be specified inline within Jenkins plugin config
### Feature Request
In my organization, every team has its own Jenkins instance running on K8S. This K8s and the instances are managed by an allocated team. 
Since this is K8s we can't just give roles to the nodes (ec2 instances) because we need segregation between the teams.
They can set [IAM role for a service account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), but we don't want to go this path because it will be hard to maintain...
Instead, we want to give the teams API keys (functional users) and roles to access the AWS secrets manager. 
The problem is they have access only to the Jenkins UI, and they can't edit the infrastructure. i.e., EnvVars, Java props, user profile authentication are out of the scope...
I would like to have the ability to set up my AWS API key+secret (or credentials id) and AWS role that will be used to pull the credentials...
p.s. Any workaround will be appreciated.

### PR DESCRIPTION
**Pull request by chriskilding**
Add a new Client CredentialsProvider configuration strategy which lets the Jenkins administrator specify an AWS static key pair for the plugin to use (`accessKey` and `secretKey`).

This is to support users who want to configure the plugin with a long-lived AWS access keypair, but who cannot modify the server that Jenkins is running on. (In this scenario, the normal methods of injecting the keypair - via the Jenkins environment or AWS profiles - are not available to them.)

Fixes #94 

Tasks:

- [x] Decide whether `accessKey` and `secretKey` are the most appropriate terms for the variables.
- [x] Add Jenkins field validations to check that `accessKey` and `secretKey` are not empty/null
- [x] Security review
  - [x] Is the keypair adequately protected within the Jenkins config by Hudson encryption?
  - [x] Is it okay to have accessKey be a plaintext field and secretKey be a protected field?
  - [x] Will field validations expose the value of `secretKey` in an undesirable way? (They look like client-side validations, but are actually implemented as AJAX requests to validation functions on the server. This means the potential secretKey value is being transmitted to the server before the form submission that saves it.)

### CODE REVIEW

**Comment by chriskilding** [comment]
In the Cloudbees AWS Credentials plugin, the accessKey is a String while the secretKey is a Hudson Secret:

https://github.com/jenkinsci/aws-credentials-plugin/blob/cbf183ce58b955f17d93fdc1ac4d19a8ebe693db/src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java

Nobody has yet disputed that, so we should probably follow the convention that has been established there

**Comment by chriskilding** [comment]
@timja If a plugin author wants a security review of a new feature/bug fix before merging it, is there a particular process to follow for that, or is it just a case of looping in reviewers on the PR like usual?

**Comment by timja** [comment]
> @timja If a plugin author wants a security review of a new feature/bug fix before merging it, is there a particular process to follow for that, or is it just a case of looping in reviewers on the PR like usual?

@jenkinsci/core-security-review might be able to take a look

**Comment by timja** [comment]
Or asking on the mailing list

**Comment by chriskilding** [comment]
Requesting a review from @Wadeck @jenkinsci/core-security-review team...

Please could you do a security review of the new feature in this PR, and let me know if it's satisfactory?

As a starter for ten, these are the security questions I can think of that need to be answered:

1. When the 'static' authentication option is chosen, the AWS keypair ends up stored in Jenkins plugin XML configuration on disk. So...
    1. Is the keypair adequately protected within the Jenkins config by Hudson encryption?
    2. Is it okay to have accessKey be a plaintext field and secretKey be a protected field? (I note that this was the approach used by the AWS Credentials type plugin.) Do we foresee any eventuality when the accessKey needs to be hidden too?
2. The Web UI has field validations to ensure that the accessKey and secretKey are not null. Will field validations expose the value of secretKey in an undesirable way? (I note that Jenkins validations look like client-side validations, but are actually implemented as AJAX requests to validation functions on the server. This means that depending on how password fields are transmitted, the potential secretKey value *could* be transmitted to the server before the form submission that saves it.)

**Comment by chriskilding** [comment]
Requesting a security review of this feature from @dwnusbaum, as Wadeck seems to be busy

**Review by Kevin-CB — APPROVED** [review]
Hello @chriskilding, from a security perspective, I see no blockers

**Comment by Kevin-CB** [comment]
> Is the keypair adequately protected within the Jenkins config by Hudson encryption?

Your secret key will be stored encrypted, see https://www.jenkins.io/doc/developer/security/secrets/#encryption-of-secrets-and-credentials

> Is it okay to have accessKey be a plaintext field and secretKey be a protected field? (I note that this was the approach used by the AWS Credentials type plugin.) Do we foresee any eventuality when the accessKey needs to be hidden too?


The accessKey is used for identifying the access key in logs, configuration, and so on. 
It could in some environments be considered sensitive data if you're looking to not release who accesses which systems and when, but it is not secret. You can find more information in the official docs (https://docs.aws.amazon.com/accounts/latest/reference/credentials-access-keys-best-practices.html)

> The Web UI has field validations to ensure that the accessKey and secretKey are not null. Will field validations expose the value of secretKey in an undesirable way?

No, these form validations won't expose your credentials, it's an UI feature to improve user experience, it won't store your credentials anywhere.

**Pull request merged**
