### PR TITLE
Use absolute path for image

### PR DESCRIPTION
**Pull request by zbynek**
This should fix rendering of the screenshot at https://plugins.jenkins.io/aws-secrets-manager-credentials-provider

### CODE REVIEW

**Comment by chriskilding** [comment]
Interesting, I'd not experienced problems with the image being resolved when the README is shown on Github. Where were you seeing the issue?

**Comment by casz** [comment]
@chriskilding see the link in the description of the PR 😆

**Comment by chriskilding** [comment]
Ah yes, I'd seen this plugin's page on jenkins.io before but didn't notice the broken image at the bottom.

**Comment by timja** [comment]
> Ah yes, I'd seen this plugin's page on jenkins.io before but didn't notice the broken image at the bottom.

FYI it won't get updated till your next release

**Comment by zbynek** [comment]
Actually only URL changes need a plugin release. Changes in the content of README are updated directly (subject to multiple cache layers, it should be visible within ca 6 hours from merge).

**Pull request merged**
