### PR TITLE
[fix] Update credential icons

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed utilizes the corresponding icon from core, which respects themes properly.
Current implementation on dark mode:
Bildschirmfoto 2022-06-23 um 00 36 29
Proposed change:
Bildschirmfoto 2022-06-23 um 00 39 23

cc @chriskilding

### CODE REVIEW

**Comment by chriskilding** [comment]
@NotMyFault do you know which Jenkins version introduced the new icon?

This plugin currently has a base of

- Jenkins 2.289
- Parent POM 2.40
- BOM 1461.vb_3c6de28f2b_a_

So I want to avoid the possibility of introducing an 'icon not found' error if these aren't new enough.

**Comment by chriskilding** [comment]
@NotMyFault I have brought the BOM dependency up to date to bring in the latest credentials-plugin version. It appears that `BasicSSHUserPrivateKey` now uses `symbol-fingerprint` for its icon - not `icon-fingerprint` as in this PR.

Is it ok to use `symbol-fingerprint` instead?

**Comment by NotMyFault** [comment]
Yes, apparently I lost track of the PR, apologizes. 

Keep in mind that Jenkinsfile modifications on my fork don't modify the Jenkinsfile revisions the PR build uses, hence the build uses 2.289.3 still.

**Comment by chriskilding** [comment]
This may also fix #246

**Pull request merged**
