### PR TITLE
Feature: Secret transformations

### PR DESCRIPTION
**Pull request by chriskilding**
Allows secret names and descriptions to be transformed.

Continuation of #31 

To do:

- [x] Config
  - [x] Web UI
  - [x] CasC
- [x] Docs
- [x] Field renaming logic + tests

### CODE REVIEW

**Comment by chriskilding** [comment]
The basic workflow (CredentialsProvider, default client) now works.

The SecretSource workflow needs property injection to work. This could be done with Java properties. Ideas below...

## JCasC-style

An idiomatic way would be to recreate the JCasC YAML hierarchy in the property's prefix. (It's even possible that JCasC might support this style of property injection already - TODO, look into this).

```properties
unclassified.awsCredentialsProvider.fields.id.replaceFirst.regex = foo-
unclassified.awsCredentialsProvider.fields.id.replaceFirst.replacement = ""
unclassified.awsCredentialsProvider.fields.description = false
```

## Fully qualified class name style

Use the fully-qualified class name that we are configuring as the property prefix. (This is the style seen in [Dropwizard Configuration](https://www.dropwizard.io/en/latest/manual/configuration.html#polymorphic-configuration).)

```properties
io.jenkins.plugins.credentials.secretsmanager.??.id.type = replaceFirst
io.jenkins.plugins.credentials.secretsmanager.??.id.regex = foo-
io.jenkins.plugins.credentials.secretsmanager.??.id.replacement = ""
io.jenkins.plugins.credentials.secretsmanager.??.description = false
```

**Comment by apottere** [comment]
This looks great!  One note about `SecretSource` is that it has to have different configuration options from `CredentialsProvider`, since in some cases it's the exact opposite behavior.  For us, `CredentialsProvider` should replace a full name path or ARN with a shorter name, but we need `SecretSource` to _add_ to the id given to get the full name or ARN that can be looked up.

**Comment by chriskilding** [comment]
On reflection the regex-based replacement would only work in the CredentialsProvider. It can't work in the SecretSource because you wouldn't know which bit of the truncated secret name you had to restore.

So to support both APIs, at minimum we would have to switch back to simple 'remove prefix' strategy - then there is no ambiguity about what part of the name to restore in the SecretSource. It would also leave the door open to a 'remove suffix' strategy being added in future, if that's something people want.

**Comment by apottere** [comment]
It depends on whether you want to be able to use the same configuration for both - I agree that a regex doesn't _really_ make sense for the `SecretSource`, but I think it would probably be ok to have different settings and different documentation for them.  I assume there are organizations out there that only want the plugin for `CredentialsProvider`, and don't use CasC and therefore don't care about the `SecretSource` settings.  Those organizations might want some sort of regex replacement.

**Comment by chriskilding** [comment]
I've pushed a rebuild which goes back to the simpler 'remove prefix' strategy in order to be compatible with the SecretSource.

This strategy *removes* the prefix (if present) from the presented credential ID in the CredentialsProvider workflow, but *adds* the prefix to restore the full secret name in the SecretSource workflow.

If the `removePrefix` configuration is set up on the PluginConfiguration object, either through CasC or the Web configuration UI, the SecretSource is able to read this configuration. That's because, although PluginConfiguration is null at the `init()` stage, it is populated at the `reveal()` stage. So if you have set the following:

```
unclassified:
  awsCredentialsProvider:
    fields:
      name:
        removePrefix:
          prefix: "foo-"
```

then the SecretSource will act on this, adding the prefix "foo-" to the supplied CasC secret name before resolving it in Secrets Manager.

We'll have to add property injection to cover the edge cases where the user hasn't set any PluginConfiguration, but this is at least a start.

**Comment by chriskilding** [comment]
If this looks like what you're after, I can give you a link to the built .hpi which you can then test drive in a local Jenkins?

**Comment by apottere** [comment]
Yeah, drop the link and I'll check it out!

**Comment by chriskilding** [comment]
Here it is... 

https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-credentials-provider-plugin/job/PR-40/12/artifact/io/jenkins/plugins/aws-secrets-manager-credentials-provider/0.5.1-rc95.e72a15bb7f39/aws-secrets-manager-credentials-provider-0.5.1-rc95.e72a15bb7f39.hpi

**Comment by chriskilding** [comment]
Hi again @apottere, did you get the chance to test this yet?

**Comment by apottere** [comment]
Sorry, not yet.  I was waiting for the slow Thanksgiving week so I could fit it in - it's on my list for tomorrow.

**Comment by apottere** [comment]
@chriskilding Sorry for such a long delay, I finally got a chance to test your branch out and it does seem to work as intended for resolving credentials and removing prefixes.  As for the `SecretSource`, on a fresh install it does seem to be unconfigured as expected:
```
i.j.p.c.s.AwsSecretSource#reveal: Secrets Manager can't find the specified secret. (Service: AWSSecretsManager; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 50bb604b-b1ea-4ee5-8c11-35e81c4090e0; Proxy: null
```

**Comment by apottere** [comment]
Also, I just realized, it might make more sense to just create a `SecretSource` configuration instead of trying to reverse the `fields.name.removePrefix` replacement.  We used different prefixes for credentials and secrets, since we only use secrets in the CasC plugin and don't need them to be resolved as credentials (and they don't have the necessary tags anyway).  Maybe add a `secretSource` configuration field that has its own `prefix`, and then users can decide if they want it to be the same or different?

**Comment by apottere** [comment]
Or omit the `secretSource` configuration on `PluginConfiguration` and require it to be configured via a java property/env variable, since it'll need that option for a clean install anyway.

**Comment by apottere** [comment]
For context, I added the following logging to the plugin.  Here's the output for a startup when `PluginConfiguration` has been removed, e.g. a fresh start (secret name replaced with `secret-name`:
```
2020-12-01 22:11:36.062+0000 [id=34]    WARNING i.j.p.c.s.AwsSecretSource#inverse: SECRET SOURCE TRANSFORMER: Default
2020-12-01 22:11:36.064+0000 [id=34]    WARNING i.j.p.c.s.AwsSecretSource#inverse: SECRET SOURCE TRANSFORMER INPUT: secret-name
2020-12-01 22:11:36.066+0000 [id=34]    WARNING i.j.p.c.s.AwsSecretSource#inverse: SECRET SOURCE TRANSFORMER OUTPUT: secret-name
```

After running again, when `PluginConfiguration` exists:
```
2020-12-01 22:07:08.397+0000 [id=31]    WARNING i.j.p.c.s.AwsSecretSource#inverse: SECRET SOURCE TRANSFORMER: RemovePrefix
2020-12-01 22:07:08.397+0000 [id=31]    WARNING i.j.p.c.s.AwsSecretSource#inverse: SECRET SOURCE TRANSFORMER INPUT: secret-name
2020-12-01 22:07:08.398+0000 [id=31]    WARNING i.j.p.c.s.AwsSecretSource#inverse: SECRET SOURCE TRANSFORMER OUTPUT: jenkins/wp-jenkins/credential/secret-name
```

Unfortunately, the name of the secret is _actually_ `jenkins/wp-jenkins/secret/secret-name`

**Comment by apottere** [comment]
All of that being said, the new configuration options worked perfectly for importing the credentials and removing the prefix from their IDs

**Comment by chriskilding** [comment]
There is a subtlety in the way the SecretSource works which means you don't need to have different prefixes for secrets vs credentials.

That is, an untagged secret is only accessible through the SecretSource.

But a secret with the `jenkins:credentials:type` tag is accessible both through the CredentialsProvider and the SecretSource.

Would this help you with the way the renaming works, and remove the need for a different configuration just for the SecretSource?

**Comment by apottere** [comment]
Yeah, that's definitely a possibility, it just makes the tooling more complicated.  Right now we have a script that assists in uploading secrets, and it's nice to be able to assume that the secrets with `/credential/` in the path are credentials and the secrets with `/secret/` in the path are for use with the `SecretSource`.  It almost seems more intuitive to separate the configuration for the `CredentialProvider` and `SecretSource` anyway, though - right now it's a little confusing what the configuration options will do unless you've read the source code.

**Comment by chriskilding** [comment]
Hi again, just to let you know I'm still thinking about this.

There are a couple of other issues that have been raised which come at this problem in different ways. The common theme is that they, like yourself, are looking for a way for a bunch of secrets to have a consistent name across environments, and then have the environment specifier injected somehow so that it doesn't pollute the pipeline scripts.

My team's own approach was that we had one Jenkins per environment (this was an arrangement that predated the development of this plugin), then apply a ListSecrets filter to restrict the secrets shown in each Jenkins to the corresponding environment.

But obviously people with a single Jenkins that straddles multiple AWS or other cloud accounts need an alternative namespacing mechanism...

You've come at it from the angle where all secrets are in one AWS account, and have the same names for each environment, except for a prefix to signify the environment that is then removed.

Another ([JENKINS-61938](https://issues.jenkins.io/browse/JENKINS-61938)) has secrets in different AWS accounts, and they also want all the secrets to have the same names in each account for consistency, and then a way to inject the AWS account ID so that the credentials provider knows which account to bind to.

It definitely feels like some kind of general namespacing mechanism is needed in Jenkins to handle cross-environment or cross-account setups. At least in the credentials system but possibly in other resources too. This is something that would be out of scope of this provider - it would have to be added to the Jenkins API plugins, and then implemented in providers.

If you have any thoughts on this I'd love to hear them - this feels like a missing abstraction in Jenkins that deserves a full solution.

**Comment by chriskilding** [comment]
My initial idea for a general namespacing mechanism looks like this...

We add a new `namespace` argument to `withCredentials` or `credentials` blocks.

Each `CredentialsProvider` then has a choice of how to implement the namespacing. It might be:
- to differentiate credentials in the same account with different prefixes
- to differentiate credentials from different accounts

The namespace could literally reflect a part of the credential's ID or locator: it could be the literal AWS account ID as shown below. But it doesn't have to be. We could have an option to define friendly names for namespaces too.

This would allow credentials with potentially the same IDs from different places to coexist comfortably with each other, without ID clashes.

If a `CredentialsProvider` does not implement the namespace feature, its credentials are deemed to be in the global default namespace. You'd continue to access those credentials as you do today, with no `namespace` argument.

## Example

Simple usage:

```groovy
node {
    withCredentials(bindings: [string(credentialsId: 'api-key', variable: 'API_KEY', namespace: '1111111111')]) {
        echo 'Hello world'
    }
}
```

Multi-namespace usage in the same script (e.g. multi-environment or multi-cloud orchestration):

```groovy
pipeline {
    agent any
    stages {
        stage('Deploy to staging') {
            environment {
                API_KEY = credentials('api-key', namespace: '1111111111')
            }
            steps {
                sh 'curl -X POST -u "foo:$API_KEY" https://example.com'
            }
        }
        stage('Deploy to production') {
            environment {
                API_KEY = credentials('api-key', namespace: '2222222222')
            }
            steps {
                sh 'curl -X POST -u "foo:$API_KEY" https://example.com'
            }
        }
    }
}
```

**Comment by apottere** [comment]
Hey, I'm still thinking about this every so often as well.  I think I've generally come to this conclusion a few times:

I think that it would be helpful to have a general namespacing pattern in Jenkins, and while what you've suggested sounds great, I'm skeptical that it would come to fruition anytime soon.  In the short term, it's just easier for us to maintain our custom fork of the plugin that supports simple environment variables for adding/removing prefixes.

**Comment by chriskilding** [comment]
@apottere As the saying goes, 'never say never'...

I've now fully extracted the SecretSource into its own plugin as of v1.0.0, which removes the single biggest impediment to implementing features that take configuration (the CredentialsProvider acts after startup so it can see Jenkins config, while the SecretSource acts at bootstrapping time so it can't see Jenkins config).

As a result, I've now reworked this renaming feature in the most recent commits. It's largely the same as before, but a couple of things have changed - e.g. it's called "Transformations" rather than "Fields" to make what it does more obvious. (See the Transformations docs page in this branch for details.)

Would you be willing to test it one more time, and if it's good I'll merge it?

**Comment by apottere** [comment]
@chriskilding Thanks for picking this back up - I'm actually at a different company now than I was when I posted here last, so unfortunately I can't test if this works where I had originally intended it to.  That being said, if you think it would benefit the project going forward then merge away!  I assume my old co-workers are still using the patched version of the plugin or have migrated away from it if they're not watching this issue.

Apologies for not letting you know I was no longer waiting around for this and potentially wasting your time, one of the loose ends I forgot to clean up when offboarding I guess :/

**Pull request merged**
