### PR TITLE
[feature] Add Remove Prefixes transformer

### PR DESCRIPTION
**Pull request by chriskilding**
Add a new secret name transformer called "Remove Prefixes".

This accepts a list of multiple prefixes, and when one of them is seen in a secret name, it is removed.

Implements #227 

## Example

Given the following configuration:

```yaml
unclassified:
  awsCredentialsProvider:
    transformations:
      name:
        removePrefixes:
          prefixes:
            - "foo-"
            - "bar-"
```

The following transformations will happen:

- the secret "foo-artifactory" is presented as the credential "artifactory".
- the secret "bar-artifactory" is presented as the credential "artifactory".

### CODE REVIEW

**Comment by chriskilding** [comment]
@andzej505hq would you be able to test this feature by dropping an experimental version of the plugin into your test Jenkins installation?

The plugin .hpi is available at

https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/aws-secrets-manager-credentials-provider/1.192.v7b_d70e8263fa_/aws-secrets-manager-credentials-provider-1.192.v7b_d70e8263fa_.hpi

**Comment by andzej505hq** [comment]
Sure, I'll try and find some time to test this. Unlikely I'll have time today, but might get it done tomorrow

**Comment by andzej505hq** [comment]
Credentials I'm using
image


This change works well when prefixes do not overlap
```yaml
awsCredentialsProvider:
    cache: true
    listSecrets:
      filters:
        - key: "name"
          values:
            - "jenkins/test"
    transformations:
      name:
        removePrefixes:
          prefixes:
            - "jenkins/test2/"
            - "jenkins/test/"
```
image

But when I introduce a shorter prefix that overlaps with longer ones, the result is not what I would expect.
```yaml
awsCredentialsProvider:
    cache: true
    listSecrets:
      filters:
        - key: "name"
          values:
            - "jenkins/test"
    transformations:
      name:
        removePrefixes:
          prefixes:
            - "jenkins/"
            - "jenkins/test2/"
            - "jenkins/test/"
```
image
It looks like the shortest prefix is applied first (are those sorted alphabetically?), so when longer ones try to match - the prefix is no longer there.

**Comment by chriskilding** [comment]
I can reproduce the problem with this unit test:

```java
@Test
public void shouldMatchTheMostSpecificPrefix() {
        assertThat(removePrefixes("aa", "aab").from("aab-secret"))
                .isEqualTo("secret");
}
```

Result:

```
org.junit.ComparisonFailure: 
Expected :"secret"
Actual   :"b-secret"
```

**Comment by chriskilding** [comment]
Before going ahead and writing this new behaviour into `PrefixRemover`, can you think of any gotchas? Any times when you would not want the longest / most specific matching prefix pattern to be the one that's removed?

**Comment by andzej505hq** [comment]
Can't think of any. I would always expect the most specific prefixes removed first.
Still, explaining this behaviour in the docs would be good

**Comment by chriskilding** [comment]
Here is an updated version of the plugin with the fix:

https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/aws-secrets-manager-credentials-provider/1.194.vd1d9b_50d0d2f/aws-secrets-manager-credentials-provider-1.194.vd1d9b_50d0d2f.hpi

I also added a note about 'longest prefix match wins' to the docs.

The revised implementation of PrefixRemover also drops the Pattern.compile... step in favour of just (1) finding the length of the longest matching prefix and (2) calling `substring` on the secret name, starting from this index. This should be a bit faster than before, though probably not quite as fast as doing the whole feature in regex (because regex engines are so highly optimised).

**Comment by chriskilding** [comment]
If you could let me know whether it fixes the issue you saw, that would be great :)

**Comment by andzej505hq** [comment]
Works as expected now 👍 
with

```yaml
awsCredentialsProvider:
    cache: true
    listSecrets:
      filters:
        - key: "name"
          values:
            - "jenkins/test"
    transformations:
      name:
        removePrefixes:
          prefixes:
            - "jenkins/"
            - "jenkins/test/"
```

image

**Comment by chriskilding** [comment]
Great 👍

**Comment by chriskilding** [comment]
Could you also check the revised version of the README in this PR (particularly the transformations page, https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/d1d9b50d0d2faa447683f6061ef4a8d14e81fb9a/docs/transformations/index.md) and let me know if it makes sense?

**Comment by andzej505hq** [comment]
I think the README is clear enough 👍

**Pull request merged**
