### PR TITLE
Bug: Git plugin always treats AwsCredentials as an SSHUserPrivateKey

### PR DESCRIPTION
**Pull request by mhaley-miovision**
continuation of https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/10.

I tried to go down the route of fixing this in the git plugin, but the assumption that if a credential object implements the `SSHUserPrivateKey` then it must be an ssh key is broken in at least two different places across at least two different plugins.  I think that it is fair for other plugins to make this assumption, and that this plugin should be a little smarter/forgiving when fetching credentials.  See https://github.com/jenkinsci/git-client-plugin/pull/484 for more context.

### CODE REVIEW

**Comment by chriskilding** [comment]
Hi Mark, after considering the options it does seem that your suggestion of introducing a `jenkins:credentials:type` tag is the only surefire way to solve this. As you mentioned there are many consuming plugins out there which assume a credentials object implements only one type, and we can't fix them all.

However, if we have auto detection for some types but manual tags for others, then users will inevitably get confused. This is one of those cases where there needs to be just one way of doing it. So on balance I believe it is better to introduce the type tag for all credentials managed by the provider, and to remove the auto detector.

This approach has additional benefits:

- Implicit secret filtering: The only Secrets Manager secrets you will see in Jenkins are the ones that you wanted it to see - the `jenkins:credentials:type` tag is an implicit signal of this.
- Correct UI behaviour: The credential binding widget in the freestyle job builder + pipeline DSL generator will only offer to bind secrets which are actually of the desired type. The credential list view will also decorate the Secrets Manager secrets in the correct type-specific way.

**Comment by chriskilding** [comment]
I've done the work for this in my branch locally, which I will attempt to push. Git is suggesting that it will overwrite your commits so I'll hold off until I hear from you.

**Comment by mhaley-miovision** [comment]
Hi Chris, I think this makes sense, the downside of having users always specify the `jenkins:credentials:type` tag is that is will be a breaking change.  I'm not sure how much of an issue that will be.

Feel free to push up your commits, and if I get some time today I can give your changes a test on my Jenkins box.

**Comment by chriskilding** [comment]
Since the project is pre-version 1, I'll release it as version 0.2.0 (which implies it is not just a bugfix increment) together with a warning of some kind.

**Comment by chriskilding** [comment]
The changes have appeared under #10 rather than here.

**Comment by mhaley-miovision** [comment]
Closing in favour of #10.

**Pull request closed without merging**
