### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by chriskilding**

### CODE REVIEW

**Comment by chriskilding** [comment]
@zbynek could you cast your eye over this and tell me if the images, and links to new pages (caching, networking, screenshots) will work on plugins.jenkins.io? Or if not, then what needs to change.

**Comment by zbynek** [comment]
I think you need to change one of two things:
a) relative -> absolute links in readme (e.g. `caching/index.md` -> `/docs/caching/index.md`)
b) `<url>` in POM to point to the README directly, i.e. https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/master/docs/README.md

Hopefully in the future anything that renders on GitHub would render properly with the plugin site -- @halkeye has made some progress in https://github.com/jenkins-infra/plugin-site-api/pull/79

**Comment by chriskilding** [comment]
The relative/absolute links in README make sense. What does the POM URL change do? (The GitHub URLs for this plugin seem to work fine already on the plugins.jenkins.io page.)

**Comment by zbynek** [comment]
>What does the POM URL change do? 

If it's the full path, the plugin site can use it to resolve relative paths correctly. If it's pointing to the repo itself, relative paths are resolved as if the readme was in the root of the repo.

**Comment by chriskilding** [comment]
Have set the POM URL to the full value, as this is preferable to making all links absolute. (Also the IntelliJ Markdown renderer only knows how to follow relative links, not absolute ones, so this way round is more convenient for developers too.)

**Pull request merged**
